### ISSUE TITLE
Should not explose uris with file scheme

### ISSUE THREAD

**Issue by friedger** [openintents/filemanager#86]
If targeting Android N+ FileUriExposedExceptions are thrown

**Comment by billthefarmer** [comment]
This is annoying - makes it difficult to test other apps. Suggest target older android version as there doesn't appear to be a workaround apart from using 'content' uris which then have to be resolved to find out what 'real' file is referenced. I have limited the target version of my apps to avoid similar 'bigbrotherness'.

**Comment by tdilo** [comment]
My change does not fix the `TestSaveAsActivity` tests which presumably got broken in f9621c3b73206634d7923a45f486632c37989634 or even earlier. The tests fail due to
`android.os.FileUriExposedException: file:///storage/emulated/0/oi-filemanager-tests/oi-to-open.txt exposed beyond app through Intent.getData()`. I was unable to fix those by adding a FileProvider to the tests, but that's most likely just lack of experience with unit testing on Android on my side.

**Comment by friedger** [comment]
I pushed 2.2.0 that should fix this. @tdilo Do you want to test?

**Comment by tdilo** [comment]
Sure thing, probably tomorrow or the day after

**Comment by tdilo** [comment]
Works well here, thanks :)

**Comment by friedger** [comment]
Thanks!
