### ISSUE TITLE
Please support the open folder intent

### ISSUE THREAD

**Issue by contrapunctus-1** [openintents/filemanager#87]
Applications like [Syncthing](https://syncthing.net/) require it to open folders.
See also https://github.com/syncthing/syncthing-android/issues/838

**Comment by veniosg** [comment]
There is no such standard Intent as far as I am aware, would you mind elaborating on the options?

**Comment by friedger** [comment]
We support the intent to pick a folder
org.openintents.action.PICK_DIRECTORY




Am 06.09.2017 09:01 schrieb "George Venios" <notifications@github.com>:

**Comment by veniosg** [comment]
If I'm not mistaken this request is for pointing the file manager to launch on an arbitrary path, but without offering any further action like "pick" - at least according to the linked issue :)

**Comment by friedger** [comment]
You want something like action VIEW with mime type like
vnd.android.documents/directory?
https://stackoverflow.com/questions/18869772/mime-type-for-a-directory

What is the URI scheme you want to view? Probably one of FileProvider.

Am 06.09.2017 09:35 schrieb "George Venios" <notifications@github.com>:

If I'm not mistaken this request is for pointing the file manager to launch
on an arbitrary path, but without offering any further action like "pick" -
at least according to the linked issue :)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/openintents/filemanager/issues/87#issuecomment-327400937>,
or mute the thread

**Comment by k3b** [comment]
goal:

* Intent to open filemanager and view content of a specified directory in the filemanager.
* This feature should not be a picker

my proposal: use this: https://stackoverflow.com/questions/17165972/android-how-to-open-a-specific-folder-via-intent-and-show-its-content-in-a-file
it already works with "EF File Explorer" 

  * action=android.intent.action.VIEW
  * data=file:/path/to/directory/
  * mime=resource/folder

**Comment by friedger** [comment]
I am worried about the non-standard mime type, as well as the FileUriExposedException when using the file schema.

Could you please propose something with FileProvider?

**Comment by k3b** [comment]
I agree that we should use the "standard".

Unfortunately there is none (at least none i am aware of or one that is widley known or widly implemented)

In my opinion the best way is to use something that other  have implemented or is willing/planning/thinking about to implement.

therefore i am lobbying for this proposal.

* https://github.com/SimpleMobileTools/Simple-File-Manager/issues/84
* https://www.ghisler.ch/board/viewtopic.php?p=323853 
* https://github.com/syncthing/syncthing-android/issues/838

If you think that we should follow an other "standard" as discussed in https://stackoverflow.com/questions/18869772/mime-type-for-a-directory it may be a compromise and easy to to implement several different "standards":

* mime=resource/folder ( already used by a few android apps. https://stackoverflow.com/questions/17165972/android-how-to-open-a-specific-folder-via-intent-and-show-its-content-in-a-file )
* mime=vnd.android.document/directory  ( used by some android document provider for GET_CONTENT )
* text/directory    ( http://tools.ietf.org/html/rfc6350 and http://tools.ietf.org/html/rfc2425#section-3 )
* inode/directory ( http://standards.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-latest.html#idm140625828597376 ) 

If you think we should use a different format, please let us know which one you like to support so i will integrate additional logic into my own ["show in filemanager"](https://github.com/k3b/APhotoManager/issues/99) logic to try different standards

---

[fileuriexposedexception since android n/sdk-24](https://stackoverflow.com/questions/41144898/android-camera-intent-fileuriexposedexception-for-sdk-24) does this mean we have to hide "file:" from android if we want to have a "show in filemanager" function in our apps ?

**Comment by friedger** [comment]
I would go for `vnd.android.document/directory` as some file managers also can show online storage. I have opened an issue at the google issue tracker for FileProvider.getType() https://issuetracker.google.com/issues/67545552

And yes, you should get ride of the file scheme.

**Comment by k3b** [comment]
ok thanks for feedback. my app will try vnd.android.document/directory and if not found try resource/folder

**Comment by friedger** [comment]
I have created a sample app on https://github.com/openintents/directory-type

As the uri does not contain any hints about the directory path, you need to add an extra string with the absolute path in your VIEW action.

I suggest something like the provider column name of MediaStore https://developer.android.com/reference/android/provider/MediaStore.MediaColumns.html#DATA or the extra to show the initial folder when opening a document https://developer.android.com/reference/android/provider/DocumentsContract.html#EXTRA_INITIAL_URI

My suggestion is
```
org.openintents.extra.ABSOLUTE_PATH
```

**Comment by k3b** [comment]
i woult propose to use org.openintents.extra.ABSOLUTE_PATH.
And if this extra is not set use data-uri. (file:uri with a directory) Other cloud-aware filemanagers can use cloud spefic directory-urls.

this way it is compatible with the other view actions without the need for a new extra parameter.

**Comment by friedger** [comment]
I have added documentation for this at 
http://www.openintents.org/action/android-intent-action-view/file-directory

Thanks for the discussion!
